const fs = require("fs").promises;

const creatureStats = {
	Alora: {
		Element: "Nature",
		"Armor Penetration": 0,
		"Critical Damage": 0,
		"Base Attack": 1.5,
	},
	Armorillo: {
		Element: "Earth",
		"Armor Penetration": 0.08,
		"Critical Damage": 0.4,
		"Base Attack": 1.25,
	},
	Bat: {
		Element: "Lightning",
		"Armor Penetration": 0,
		"Critical Damage": 0.9,
		"Base Attack": 1.55,
	},
	Blok: {
		Element: "Earth",
		"Armor Penetration": 0,
		"Critical Damage": 0,
		"Base Attack": 1.55,
	},
	Boar: {
		Element: "Nature",
		"Armor Penetration": 0.05,
		"Critical Damage": 0.25,
		"Base Attack": 1.5,
	},
	Boris: {
		Element: "Nature",
		"Armor Penetration": 0,
		"Critical Damage": 0,
		"Base Attack": 1.45,
	},
	Breff: {
		Element: "Frost",
		"Armor Penetration": 0.05,
		"Critical Damage": 0.2,
		"Base Attack": 1.5,
	},
	Bullrock: {
		Element: "Fire",
		"Armor Penetration": 0,
		"Critical Damage": 0.15,
		"Base Attack": 1.5,
	},
	Cackler: {
		Element: "Earth",
		"Armor Penetration": 0.08,
		"Critical Damage": 0.4,
		"Base Attack": 1.5,
	},
	Cerberus: {
		Element: "Fire",
		"Armor Penetration": 0,
		"Critical Damage": 0.2,
		"Base Attack": 1.55,
	},
	Chopjaw: {
		Element: "Water",
		"Armor Penetration": 0.1,
		"Critical Damage": 0.3,
		"Base Attack": 1.65,
	},
	"Cliff Goat": {
		Element: "",
		"Armor Penetration": 0.1,
		"Critical Damage": 0.3,
		"Base Attack": 1.65,
	},
	Crow: {
		Element: "Nature",
		"Armor Penetration": 0,
		"Critical Damage": 0.25,
		"Base Attack": 1.25,
	},
	Crushling: {
		Element: "Earth",
		"Armor Penetration": 0,
		"Critical Damage": 0.8,
		"Base Attack": 1.1,
	},
	Demon: {
		Element: "Fire",
		"Armor Penetration": 0,
		"Critical Damage": 0.25,
		"Base Attack": 1.65,
	},
	"Dire Bear": {
		Element: "Nature",
		"Armor Penetration": 0.2,
		"Critical Damage": 0.15,
		"Base Attack": 1.7,
	},
	Douseling: {
		Element: "Water",
		"Armor Penetration": 0,
		"Critical Damage": 0.9,
		"Base Attack": 1.2,
	},
	Drainling: {
		Element: "Void",
		"Armor Penetration": 0.05,
		"Critical Damage": 0.9,
		"Base Attack": 1.15,
	},
	Drakbarn: {
		Element: "Earth",
		"Armor Penetration": 0,
		"Critical Damage": 0.25,
		"Base Attack": 1.3,
	},
	Drylard: {
		Element: "Earth",
		"Armor Penetration": 0,
		"Critical Damage": 0.15,
		"Base Attack": 1.45,
	},
	Dunder: {
		Element: "Lightning",
		"Armor Penetration": 0,
		"Critical Damage": 0,
		"Base Attack": 1.45,
	},
	"Earth Elemental": {
		Element: "Earth",
		"Armor Penetration": 0.05,
		"Critical Damage": 0.25,
		"Base Attack": 1.8,
	},
	Elise: {
		Element: "Earth",
		"Armor Penetration": 0,
		"Critical Damage": 0,
		"Base Attack": 1.4,
	},
	"Ember Fiend": {
		Element: "Fire",
		"Armor Penetration": 0.05,
		"Critical Damage": 0.3,
		"Base Attack": 1.45,
	},
	"Erat Herba": {
		Element: "",
		"Armor Penetration": 0,
		"Critical Damage": 0.25,
		"Base Attack": 2.0,
	},
	Ettlok: {
		Element: "Earth",
		"Armor Penetration": 0.05,
		"Critical Damage": 0.25,
		"Base Attack": 1.4,
	},
	"Fire Elemental": {
		Element: "Fire",
		"Armor Penetration": 0.1,
		"Critical Damage": 0.4,
		"Base Attack": 1.7,
	},
	"Fluctus Thadal": {
		Element: "Water",
		"Armor Penetration": 0,
		"Critical Damage": 0.15,
		"Base Attack": 1.85,
	},
	Freezeling: {
		Element: "Frost",
		"Armor Penetration": 0,
		"Critical Damage": 0.1,
		"Base Attack": 1.4,
	},
	"Frigus Mortis": {
		Element: "Frost",
		"Armor Penetration": 0.15,
		"Critical Damage": 0.33,
		"Base Attack": 1.6,
	},
	"Frost Elemental": {
		Element: "Frost",
		"Armor Penetration": 0.3,
		"Critical Damage": 0.9,
		"Base Attack": 1.7,
	},
	Giant: {
		Element: "Fire",
		"Armor Penetration": 0.8,
		"Critical Damage": 0.75,
		"Base Attack": 1.5,
	},
	Giant: {
		Element: "Earth",
		"Armor Penetration": 0.8,
		"Critical Damage": 0.75,
		"Base Attack": 1.5,
	},
	Giant: {
		Element: "Nature",
		"Armor Penetration": 0.8,
		"Critical Damage": 0.75,
		"Base Attack": 1.5,
	},
	Giant: {
		Element: "Lightning",
		"Armor Penetration": 0.8,
		"Critical Damage": 0.75,
		"Base Attack": 1.5,
	},
	Giant: {
		Element: "Water",
		"Armor Penetration": 0.8,
		"Critical Damage": 0.75,
		"Base Attack": 1.5,
	},
	Giant: {
		Element: "Frost",
		"Armor Penetration": 0.8,
		"Critical Damage": 0.75,
		"Base Attack": 1.5,
	},
	Goblin: {
		Element: "Fire",
		"Armor Penetration": 0,
		"Critical Damage": 0.9,
		"Base Attack": 1.55,
	},
	Golem: {
		Element: "Earth",
		"Armor Penetration": 0.2,
		"Critical Damage": 0.15,
		"Base Attack": 1.7,
	},
	Healling: {
		Element: "Nature",
		"Armor Penetration": 0,
		"Critical Damage": 0.2,
		"Base Attack": 1.35,
	},
	Herald: {
		Element: "Lightning",
		"Armor Penetration": 0.1,
		"Critical Damage": 0.25,
		"Base Attack": 1.7,
	},
	Hexapus: {
		Element: "Water",
		"Armor Penetration": 0,
		"Critical Damage": 0.4,
		"Base Attack": 1.35,
	},
	Hydro: {
		Element: "Water",
		"Armor Penetration": 0,
		"Critical Damage": 0,
		"Base Attack": 1.8,
	},
	Icear: {
		Element: "Frost",
		"Armor Penetration": 0,
		"Critical Damage": 0.25,
		"Base Attack": 1.5,
	},
	Ishana: {
		Element: "Void",
		"Armor Penetration": 0,
		"Critical Damage": 0,
		"Base Attack": 1.58,
	},
	Justin: {
		Element: "Water",
		"Armor Penetration": 0,
		"Critical Damage": 0,
		"Base Attack": 1.55,
	},
	Kyl: {
		Element: "Frost",
		"Armor Penetration": 0,
		"Critical Damage": 0,
		"Base Attack": 1.64,
	},
	Leviathan: {
		Element: "Water",
		"Armor Penetration": 0.9,
		"Critical Damage": 0.5,
		"Base Attack": 1.5,
	},
	"Lightning Elemental": {
		Element: "Lightning",
		"Armor Penetration": 0.1,
		"Critical Damage": 0.4,
		"Base Attack": 1.7,
	},
	Mammoth: {
		Element: "Frost",
		"Armor Penetration": 0.1,
		"Critical Damage": 0.25,
		"Base Attack": 1.5,
	},
	Mauler: {
		Element: "Earth",
		"Armor Penetration": 0,
		"Critical Damage": 0.6,
		"Base Attack": 1.4,
	},
	Minotaur: {
		Element: "Nature",
		"Armor Penetration": 0,
		"Critical Damage": 0.9,
		"Base Attack": 1.6,
	},
	Moa: {
		Element: "Lightning",
		"Armor Penetration": 0.1,
		"Critical Damage": 0.9,
		"Base Attack": 1.3,
	},
	"Mons Igneus": {
		Element: "Fire",
		"Armor Penetration": 0,
		"Critical Damage": 0.3,
		"Base Attack": 1.7,
	},
	"Nature Elemental": {
		Element: "Nature",
		"Armor Penetration": 0,
		"Critical Damage": 0.9,
		"Base Attack": 1.45,
	},
	"Nullius Terram": {
		Element: "Void",
		"Armor Penetration": 0,
		"Critical Damage": 0,
		"Base Attack": 1.6,
	},
	Onkh: {
		Element: "Lightning",
		"Armor Penetration": 0,
		"Critical Damage": 0.2,
		"Base Attack": 1.55,
	},
	Oskar: {
		Element: "Lightning",
		"Armor Penetration": 0,
		"Critical Damage": 0,
		"Base Attack": 1.6,
	},
	"Owl Bear": {
		Element: "Nature",
		"Armor Penetration": 0.1,
		"Critical Damage": 0.3,
		"Base Attack": 1.55,
	},
	Ragnar: {
		Element: "Fire",
		"Armor Penetration": 0,
		"Critical Damage": 0,
		"Base Attack": 1.8,
	},
	Roc: {
		Element: "Frost",
		"Armor Penetration": 0,
		"Critical Damage": 0.25,
		"Base Attack": 1.35,
	},
	"Rock Horn": {
		Element: "Earth",
		"Armor Penetration": 0.05,
		"Critical Damage": 0.4,
		"Base Attack": 1.5,
	},
	"Rune Stag": {
		Element: "Nature",
		"Armor Penetration": 0,
		"Critical Damage": 0.15,
		"Base Attack": 1.85,
	},
	Scorchling: {
		Element: "Fire",
		"Armor Penetration": 0,
		"Critical Damage": 0.25,
		"Base Attack": 1.3,
	},
	Scorpion: {
		Element: "Earth",
		"Armor Penetration": 0,
		"Critical Damage": 0.25,
		"Base Attack": 1.45,
	},
	"Sea Horse": {
		Element: "Water",
		"Armor Penetration": 0,
		"Critical Damage": 0.15,
		"Base Attack": 1.45,
	},
	Serpenta: {
		Element: "Water",
		"Armor Penetration": 0,
		"Critical Damage": 0.6,
		"Base Attack": 1.4,
	},
	Shockling: {
		Element: "Lightning",
		"Armor Penetration": 0,
		"Critical Damage": 0.25,
		"Base Attack": 1.3,
	},
	Snake: {
		Element: "Nature",
		"Armor Penetration": 0.1,
		"Critical Damage": 0.25,
		"Base Attack": 1.35,
	},
	Spiderling: {
		Element: "Nature",
		"Armor Penetration": 0,
		"Critical Damage": 0,
		"Base Attack": 1.1,
	},
	Steppa: {
		Element: "Fire",
		"Armor Penetration": 0,
		"Critical Damage": 0.1,
		"Base Attack": 1.2,
	},
	Treefolk: {
		Element: "Nature",
		"Armor Penetration": 0.08,
		"Critical Damage": 0.08,
		"Base Attack": 1.4,
	},
	Troll: {
		Element: "Nature",
		"Armor Penetration": 0.3,
		"Critical Damage": 0.4,
		"Base Attack": 1.75,
	},
	Turtle: {
		Element: "Water",
		"Armor Penetration": 0,
		"Critical Damage": 0.5,
		"Base Attack": 1.25,
	},
	Ulwar: {
		Element: "Lightning",
		"Armor Penetration": 0.15,
		"Critical Damage": 0.3,
		"Base Attack": 1.55,
	},
	"Vento Mico": {
		Element: "Lightning",
		"Armor Penetration": 0,
		"Critical Damage": 0.15,
		"Base Attack": 1.85,
	},
	"Vita Deserto": {
		Element: "Earth",
		"Armor Penetration": 0,
		"Critical Damage": 0.75,
		"Base Attack": 1.55,
	},
	"Void Elemental": {
		Element: "Void",
		"Armor Penetration": 0.05,
		"Critical Damage": 0.25,
		"Base Attack": 1.8,
	},
	Warrus: {
		Element: "Frost",
		"Armor Penetration": 0,
		"Critical Damage": 0,
		"Base Attack": 1.45,
	},
	"Water Elemental": {
		Element: "Water",
		"Armor Penetration": 0.15,
		"Critical Damage": 0.3,
		"Base Attack": 1.55,
	},
	Wolf: {
		Element: "Frost",
		"Armor Penetration": 0,
		"Critical Damage": 0.25,
		"Base Attack": 1.35,
	},
	Wurm: {
		Element: "Fire",
		"Armor Penetration": 0.15,
		"Critical Damage": 0.9,
		"Base Attack": 1.45,
	},
	Wyn: {
		Element: "Fire",
		"Armor Penetration": 0,
		"Critical Damage": 0,
		"Base Attack": 1.65,
	},
	Wyvern: {
		Element: "Lightning",
		"Armor Penetration": 0.05,
		"Critical Damage": 0.25,
		"Base Attack": 1.5,
	},
	Yeti: {
		Element: "Frost",
		"Armor Penetration": 0.15,
		"Critical Damage": 0.25,
		"Base Attack": 1.5,
	},
};

const data = JSON.stringify(creatureStats, null, 4);

const writeCreatureStats = () => {
	fs.writeFile("./src/creatureStats/creatureStats.json", data, (err) => {
		if (err) {
			throw err;
		}
		console.log("JSON data is saved.");
	});
};

// for adding in new entries -->   '': {'Element': '', 'Armor Penetration': 0, 'Critical Damage': 0, 'Base Attack': },

module.exports = {
	writeCreatureStats,
};
