import { writeFile } from 'fs';

const creatureStats = {
    'Alora': {'Element': 'Nature', 'Armor Penetration': 0, 'Critical Damage': 0, 'Base Attack': 1.50},
    'Armorillo': {'Element': 'Earth', 'Armor Penetration': 0.08, 'Critical Damage': 0.4, 'Base Attack': 1.25},
    'Bat': {'Element': 'Lightning', 'Armor Penetration': 0, 'Critical Damage': 0.9, 'Base Attack': 1.55},
    'Blok': {'Element': 'Earth', 'Armor Penetration': 0, 'Critical Damage': 0, 'Base Attack': 1.55},
    'Boar': {'Element': 'Nature', 'Armor Penetration': 0.05, 'Critical Damage': 0.25, 'Base Attack': 1.5},
    'Boris': {'Element': 'Nature', 'Armor Penetration': 0, 'Critical Damage': 0, 'Base Attack': 1.45},
    'Breff': {'Element': 'Frost', 'Armor Penetration': 0.05, 'Critical Damage': 0.2, 'Base Attack': 1.50},
    'Bullrock': {'Element': 'Fire', 'Armor Penetration': 0, 'Critical Damage': 0.15, 'Base Attack': 1.50},
    'Cackler': {'Element': 'Earth', 'Armor Penetration': 0.08, 'Critical Damage': 0.4, 'Base Attack': 1.50},
    'Cerberus': {'Element': 'Fire', 'Armor Penetration': 0, 'Critical Damage': 0.2, 'Base Attack': 1.55},
    'Chopjaw': {'Element': 'Water', 'Armor Penetration': 0.1, 'Critical Damage': 0.3, 'Base Attack': 1.65},
    'Cliff Goat': {'Element': '', 'Armor Penetration': 0.1, 'Critical Damage': 0.3, 'Base Attack': 1.65},
    'Crow': {'Element': 'Nature', 'Armor Penetration': 0, 'Critical Damage': 0.25, 'Base Attack': 1.25},
    'Crushling': {'Element': 'Earth', 'Armor Penetration': 0, 'Critical Damage': 0.8, 'Base Attack': 1.10},
    'Demon': {'Element': 'Fire', 'Armor Penetration': 0, 'Critical Damage': 0.25, 'Base Attack': 1.65},
    'Dire Bear': {'Element': 'Nature', 'Armor Penetration': 0.2, 'Critical Damage': 0.15, 'Base Attack': 1.70},
    'Douseling': {'Element': 'Water', 'Armor Penetration': 0, 'Critical Damage': .90, 'Base Attack': 1.20},
    'Drainling': {'Element': 'Void', 'Armor Penetration': 0.05, 'Critical Damage': 0.9, 'Base Attack': 1.15},
    'Drakbarn': {'Element': 'Earth', 'Armor Penetration': 0, 'Critical Damage': 0.25, 'Base Attack': 1.30},
    'Drylard': {'Element': 'Earth', 'Armor Penetration': 0, 'Critical Damage': 0.15, 'Base Attack': 1.45},
    'Dunder': {'Element': 'Lightning', 'Armor Penetration': 0, 'Critical Damage': 0, 'Base Attack': 1.45},
    'Earth Elemental': {'Element': 'Earth', 'Armor Penetration': 0.05, 'Critical Damage': 0.25, 'Base Attack': 1.80},
    'Elise': {'Element': 'Earth', 'Armor Penetration': 0, 'Critical Damage': 0, 'Base Attack': 1.40},
    'Ember Fiend': {'Element': 'Fire', 'Armor Penetration': 0.05, 'Critical Damage': 0.3, 'Base Attack': 1.45},
    'Erat Herba': {'Element': '', 'Armor Penetration': 0, 'Critical Damage': 0.25, 'Base Attack': 2.00},
    'Ettlok': {'Element': 'Earth', 'Armor Penetration': 0.05, 'Critical Damage': 0.25, 'Base Attack': 1.40},
    'Fire Elemental': {'Element': 'Fire', 'Armor Penetration': 0.1, 'Critical Damage': 0.4, 'Base Attack': 1.70},
    'Fluctus Thadal': {'Element': 'Water', 'Armor Penetration': 0, 'Critical Damage': 0.15, 'Base Attack': 1.85},
    'Freezeling': {'Element': 'Frost', 'Armor Penetration': 0, 'Critical Damage': 0.1, 'Base Attack': 1.40},
    'Frigus Mortis': {'Element': 'Frost', 'Armor Penetration': 0.15, 'Critical Damage': 0.33, 'Base Attack': 1.60},
    'Frost Elemental': {'Element': 'Frost', 'Armor Penetration': 0.3, 'Critical Damage': 0.9, 'Base Attack': 1.70},
    'Giant': {'Element': 'Fire', 'Armor Penetration': 0.8, 'Critical Damage': 0.75, 'Base Attack': 1.50},
    'Giant': {'Element': 'Earth', 'Armor Penetration': 0.8, 'Critical Damage': 0.75, 'Base Attack': 1.50},
    'Giant': {'Element': 'Nature', 'Armor Penetration': 0.8, 'Critical Damage': 0.75, 'Base Attack': 1.50},
    'Giant': {'Element': 'Lightning', 'Armor Penetration': 0.8, 'Critical Damage': 0.75, 'Base Attack': 1.50},
    'Giant': {'Element': 'Water', 'Armor Penetration': 0.8, 'Critical Damage': 0.75, 'Base Attack': 1.50},
    'Giant': {'Element': 'Frost', 'Armor Penetration': 0.8, 'Critical Damage': 0.75, 'Base Attack': 1.50},
    'Goblin': {'Element': 'Fire', 'Armor Penetration': 0, 'Critical Damage': 0.9, 'Base Attack': 1.55},
    'Golem': {'Element': 'Earth', 'Armor Penetration': 0.2, 'Critical Damage': 0.15, 'Base Attack': 1.70},
    'Healling': {'Element': 'Nature', 'Armor Penetration': 0, 'Critical Damage': 0.2, 'Base Attack': 1.35},
    'Herald': {'Element': 'Lightning', 'Armor Penetration': 0.1, 'Critical Damage': 0.25, 'Base Attack': 1.70},
    'Hexapus': {'Element': 'Water', 'Armor Penetration': 0, 'Critical Damage': 0.4, 'Base Attack': 1.35},
    'Hydro': {'Element': 'Water', 'Armor Penetration': 0, 'Critical Damage': 0, 'Base Attack': 1.80},
    'Icear': {'Element': 'Frost', 'Armor Penetration': 0, 'Critical Damage': 0.25, 'Base Attack': 1.50},
    'Ishana': {'Element': 'Void', 'Armor Penetration': 0, 'Critical Damage': 0, 'Base Attack': 1.58},
    'Justin': {'Element': 'Water', 'Armor Penetration': 0, 'Critical Damage': 0, 'Base Attack': 1.55},
    'Kyl': {'Element': 'Frost', 'Armor Penetration': 0, 'Critical Damage': 0, 'Base Attack': 1.64},
    'Leviathan': {'Element': 'Water', 'Armor Penetration': 0.9, 'Critical Damage': 0.5, 'Base Attack': 1.50},
    'Lightning Elemental': {'Element': 'Lightning', 'Armor Penetration': 0.1, 'Critical Damage': 0.4, 'Base Attack': 1.70},
    'Mammoth': {'Element': 'Frost', 'Armor Penetration': 0.1, 'Critical Damage': 0.25, 'Base Attack': 1.50},
    'Mauler': {'Element': 'Earth', 'Armor Penetration': 0, 'Critical Damage': 0.6, 'Base Attack': 1.40},
    'Minotaur': {'Element': 'Nature', 'Armor Penetration': 0, 'Critical Damage': 0.9, 'Base Attack': 1.60},
    'Moa': {'Element': 'Lightning', 'Armor Penetration': 0.1, 'Critical Damage': 0.9, 'Base Attack': 1.30},
    'Mons Igneus': {'Element': 'Fire', 'Armor Penetration': 0, 'Critical Damage': 0.3, 'Base Attack': 1.70},
    'Nature Elemental': {'Element': 'Nature', 'Armor Penetration': 0, 'Critical Damage': 0.9, 'Base Attack': 1.45},
    'Nullius Terram': {'Element': 'Void', 'Armor Penetration': 0, 'Critical Damage': 0, 'Base Attack': 1.60},
    'Onkh': {'Element': 'Lightning', 'Armor Penetration': 0, 'Critical Damage': 0.2, 'Base Attack': 1.55},
    'Oskar': {'Element': 'Lightning', 'Armor Penetration': 0, 'Critical Damage': 0, 'Base Attack': 1.60},
    'Owl Bear': {'Element': 'Nature', 'Armor Penetration': 0.1, 'Critical Damage': 0.3, 'Base Attack': 1.55},
    'Ragnar': {'Element': 'Fire', 'Armor Penetration': 0, 'Critical Damage': 0, 'Base Attack': 1.80},
    'Roc': {'Element': 'Frost', 'Armor Penetration': 0, 'Critical Damage': 0.25, 'Base Attack': 1.35},
    'Rock Horn': {'Element': 'Earth', 'Armor Penetration': 0.05, 'Critical Damage': 0.4, 'Base Attack': 1.50},
    'Rune Stag': {'Element': 'Nature', 'Armor Penetration': 0, 'Critical Damage': 0.15, 'Base Attack': 1.85},
    'Scorchling': {'Element': 'Fire', 'Armor Penetration': 0, 'Critical Damage': 0.25, 'Base Attack': 1.30},
    'Scorpion': {'Element': 'Earth', 'Armor Penetration': 0, 'Critical Damage': 0.25, 'Base Attack': 1.45},
    'Sea Horse': {'Element': 'Water', 'Armor Penetration': 0, 'Critical Damage': 0.15, 'Base Attack': 1.45},
    'Serpenta': {'Element': 'Water', 'Armor Penetration': 0, 'Critical Damage': 0.6, 'Base Attack': 1.40},
    'Shockling': {'Element': 'Lightning', 'Armor Penetration': 0, 'Critical Damage': 0.25, 'Base Attack': 1.30},
    'Snake': {'Element': 'Nature', 'Armor Penetration': 0.1, 'Critical Damage': 0.25, 'Base Attack': 1.35},
    'Spiderling': {'Element': 'Nature', 'Armor Penetration': 0, 'Critical Damage': 0, 'Base Attack': 1.10},
    'Steppa': {'Element': 'Fire', 'Armor Penetration': 0, 'Critical Damage': 0.1, 'Base Attack': 1.20},
    'Treefolk': {'Element': 'Nature', 'Armor Penetration': 0.08, 'Critical Damage': 0.08, 'Base Attack': 1.40},
    'Troll': {'Element': 'Nature', 'Armor Penetration': 0.3, 'Critical Damage': 0.4, 'Base Attack': 1.75},
    'Turtle': {'Element': 'Water', 'Armor Penetration': 0, 'Critical Damage': 0.5, 'Base Attack': 1.25},
    'Ulwar': {'Element': 'Lightning', 'Armor Penetration': 0.15, 'Critical Damage': 0.3, 'Base Attack': 1.55},
    'Vento Mico': {'Element': 'Lightning', 'Armor Penetration': 0, 'Critical Damage': 0.15, 'Base Attack': 1.85},
    'Vita Deserto': {'Element': 'Earth', 'Armor Penetration': 0, 'Critical Damage': 0.75, 'Base Attack': 1.55},
    'Void Elemental': {'Element': 'Void', 'Armor Penetration': 0.05, 'Critical Damage': 0.25, 'Base Attack': 1.80},
    'Warrus': {'Element': 'Frost', 'Armor Penetration': 0, 'Critical Damage': 0, 'Base Attack': 1.45},
    'Water Elemental': {'Element': 'Water', 'Armor Penetration': 0.15, 'Critical Damage': 0.30, 'Base Attack': 1.55},
    'Wolf': {'Element': 'Frost', 'Armor Penetration': 0, 'Critical Damage': 0.25, 'Base Attack': 1.35},
    'Wurm': {'Element': 'Fire', 'Armor Penetration': 0.15, 'Critical Damage': 0.9, 'Base Attack': 1.45},
    'Wyn': {'Element': 'Fire', 'Armor Penetration': 0, 'Critical Damage': 0, 'Base Attack': 1.65},
    'Wyvern': {'Element': 'Lightning', 'Armor Penetration': 0.05, 'Critical Damage': 0.25, 'Base Attack': 1.50},
    'Yeti': {'Element': 'Frost', 'Armor Penetration': 0.15, 'Critical Damage': 0.25, 'Base Attack': 1.50},
};

const data = JSON.stringify(creatureStats, null, 4)

writeFile('./src/json/creatureStats.json', data, (err) => {
    if (err) {
        throw err;
    }
    console.log("JSON data is saved.");
});

// for adding in new entries -->   '': {'Element': '', 'Armor Penetration': 0, 'Critical Damage': 0, 'Base Attack': },